configuration: Release

before_build:
  - dotnet restore
  - nuget restore
 
 
build:
  project: AirportInfo.sln
  verbosity: minimal
  publish_wap: true

test:
  assemblies:
    AirportInfo.MyTest.dll

artifacts:
  - path: AirportData\bin\Debug\AirportData.dll
    name: AirportData.dll