configuration: Debug

before_build:
  - nuget restore
 
 
build:
  project: AirportInfo.sln
  verbosity: minimal
  publish_wap: true

test:
  assemblies:
    AirportInfo.MyTest.dll

artifacts:
  - path: AirportData\bin\Debug\AirportData.dll
    name: AirportData.dll

test_script:
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\AirportInfo.MyTest\bin\Debug\AirportInfo.MyTest.dll -noshadow" -filter:"+[AirportInfo.view*]*" -output:".\coverage.xml"
 - .\packages\Codecov.1.0.3\tools\codecov.exe -f "coverage.xml"